# build
FROM index.docker.io/library/ubuntu:xenial
MAINTAINER qinka <me@qinka.pro>
RUN apt update && apt install -y libgmp10 curl gnupg
RUN curl http://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
RUN echo deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main > /etc/apt/sources.list.d/llvm.list
RUN apt update && apt install -y llvm-4.0
ADD bin /usr/bin
COPY entrypoint.sh entrypoint
ENTRYPOINT ["/entrypoint"]
EXPOSE 3000
