# The config of Travis

#to use ubuntu 14.04
sudo: required
dist: trusty

# setting cache
cache:
  - $HOME/.stack
# the matrix of settings
matrix:
  include:
    - env: GHC_VER=8.0.2 IS_DOCKER=docker TARGET=toy-backend-core TARGET_FLAG='--flag toy-backend-regress:quadratic-curve' TARGET_NAME=-linear EXECUTABLE=toy-backend-core LLVM=3.7 SUDO=sudo TF_TYPE=gpu
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - curl
            - wget
    - env: GHC_VER=8.0.2 IS_DOCKER=docker TARGET=toy-backend-core TARGET_FLAG='--flag toy-backend-regress:quadratic-curve' TARGET_NAME=-linear EXECUTABLE=toy-backend-core LLVM=3.7 SUDO=sudo TF_TYPE=cpu
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - curl
            - wget
    - env: GHC_VER=8.0.2 IS_DOCKER=docker TARGET=toy-backend-core TARGET_FLAG='--flag toy-backend-regress:linear' TARGET_NAME=-linear EXECUTABLE=toy-backend-core LLVM=3.7 SUDO=sudo TF_TYPE=gpu
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - curl
            - wget
    - env: GHC_VER=8.0.2 IS_DOCKER=docker TARGET=toy-backend-core TARGET_FLAG='--flag toy-backend-regress:linear' TARGET_NAME=-linear EXECUTABLE=toy-backend-core LLVM=3.7 SUDO=sudo TF_TYPE=cpu
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - curl
            - wget
    - env: GHC_VER=8.0.2 IS_DOCKER=docker TARGET=toy-backend-core TARGET_FLAG='--flag toy-backend-classify:nn' TARGET_NAME=-nn EXECUTABLE=toy-backend-core LLVM=3.7 SUDO=sudo TF_TYPE=gpu
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - curl
            - wget
    - env: GHC_VER=8.0.2 IS_DOCKER=docker TARGET=toy-backend-core TARGET_FLAG='--flag toy-backend-classify:nn' TARGET_NAME=-nn EXECUTABLE=toy-backend-core LLVM=3.7 SUDO=sudo TF_TYPE=cpu
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - curl
            - wget
    - env: GHC_VER=8.0.2 IS_DOCKER=docker TARGET=toy-backend-core TARGET_FLAG='--flag toy-backend-classify:-knn' TARGET_NAME=-knn EXECUTABLE=toy-backend-core LLVM=3.7 SUDO=sudo 
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - curl
            - wget
    - env: GHC_VER=8.0.2 IS_DOCKER=docker TARGET=toy-backend-core TARGET_FLAG='--flag toy-backend-classify:knn-llvm-native' TARGET_NAME=-knn-llvm-native EXECUTABLE=toy-backend-core LLVM=3.7 SUDO=sudo LLVM_NATIVE=true
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - curl
            - wget
    - env: GHC_VER=8.0.2 IS_DOCKER=docker TARGET=toy-backend-core TARGET_FLAG='--flag toy-backend-classify:knn-llvm-ptx' TARGET_NAME=-knn-llvm-ptx EXECUTABLE=toy-backend-core LLVM=3.7 SUDO=sudo LLVM_PTX=true
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - curl
            - wget
    - env: GHC_VER=8.0.2 IS_DOCKER=docker TARGET=toy-backend-core TARGET_FLAG='--flag toy-backend-classify:svm' TARGET_NAME=-svm EXECUTABLE=toy-backend-core LLVM=3.7 SUDO=sudo
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - curl
            - wget
    - env: GHC_VER=8.0.2 IS_DOCKER=docker TARGET=toy-backend-core TARGET_FLAG='--flag toy-backend-classify:decision-tree' TARGET_NAME=-dt EXECUTABLE=toy-backend-core LLVM=3.7 SUDO=sudo
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - curl
            - wget
    - env: GHC_VER=8.0.2 IS_DOCKER=docker TARGET=toy-backend-core TARGET_NAME=-display EXECUTABLE=toy-backend-core LLVM=3.7 SUDO=sudo
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - curl
            - wget
            
# using docker
services:
  - docker

# pre-install
before_install:
  - source $TRAVIS_BUILD_DIR/.integration/shellscript/before.sh

# build
script:
  - source $TRAVIS_BUILD_DIR/.integration/shellscript/build.sh

# update docker image
after_success:
  - source $TRAVIS_BUILD_DIR/.integration/shellscript/after.sh
