# The config of Travis

#to use ubuntu 14.04
sudo: required
dist: trusty

# setting cache
cache:
  - $HOME/.stack
# the matrix of settings
matrix:
  include:
    - env: GHC_VER=8.0.2 IS_DOCKER=docker TARGET=nao-classify-server TARGET_FLAG='--flag nao-classify-server:decision-tree' TARGET_NAME=-dt EXECUTABLE=nao-classify-server LLVM=3.7 SUDO=sudo
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - curl
            - wget
    - env: GHC_VER=8.0.2 IS_DOCKER=docker TARGET=nao-classify-server TARGET_NAME=-display EXECUTABLE=nao-classify-server LLVM=3.7 SUDO=sudo
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - curl
            - wget
    - env: GHC_VER=8.0.2 IS_DOCKER=docker TARGET=nao-classify-server TARGET_FLAG='--flag nao-classify-server:-knn' TARGET_NAME=-knn EXECUTABLE=nao-classify-server LLVM=3.7 SUDO=sudo
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - curl
            - wget
    - env: GHC_VER=8.0.2 IS_DOCKER=docker TARGET=nao-classify-server TARGET_FLAG='--flag nao-classify-server:knn-llvm-native' TARGET_NAME=-knn-llvm-native EXECUTABLE=nao-classify-server LLVM=3.7 SUDO=sudo
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - curl
            - wget
    - env: GHC_VER=8.0.2 IS_DOCKER=docker TARGET=nao-classify-server TARGET_FLAG='--flag nao-classify-server:knn-llvm-ptx' TARGET_NAME=-knn-llvm-ptx EXECUTABLE=nao-classify-server LLVM=3.7 SUDO=sudo
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - curl
            - wget
    - env: GHC_VER=8.0.2 IS_DOCKER=docker TARGET=nao-classify-server TARGET_FLAG='--flag nao-classify-server:svm' TARGET_NAME=-svm EXECUTABLE=nao-classify-server LLVM=3.7 SUDO=sudo
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - curl
            - wget
    - env: GHC_VER=8.0.2 IS_DOCKER=docker TARGET=nao-classify-server TARGET_FLAG='--flag nao-classify-server:nn' TARGET_NAME=-nn EXECUTABLE=nao-classify-server LLVM=3.7 SUDO=sudo TF_TYPE=gpu
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - curl
            - wget
    - env: GHC_VER=8.0.2 IS_DOCKER=docker TARGET=nao-classify-server TARGET_FLAG='--flag nao-classify-server:nn' TARGET_NAME=-nn EXECUTABLE=nao-classify-server LLVM=3.7 SUDO=sudo TF_TYPE=cpu
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2
            - curl
            - wget
            
# using docker
services:
  - docker

# pre-install
before_install:
  - source $TRAVIS_BUILD_DIR/.integration/shellscript/before.sh

# build
script:
  - source $TRAVIS_BUILD_DIR/.integration/shellscript/build.sh

# update docker image
after_success:
  - source $TRAVIS_BUILD_DIR/.integration/shellscript/after.sh
