flags: {}
extra-package-dbs: []
packages:
- decision-tree/decision-tree
- decision-tree/train-decision-tree
- toy-backend/toy-backend-core
- toy-backend/toy-backend-classify
- toy-backend/toy-backend-regress
- knn
- svm/Simple-SVM
- svm/Simple-SVM/bindings-svm
- nn/neural-network
- regress
- tensorflow/tensorflow
- tensorflow/tensorflow-core-ops
- tensorflow/tensorflow-ops
- tensorflow/tensorflow-proto
resolver: nightly-2017-07-25
# compiler: ghc-8.2.1
extra-deps:
- accelerate-llvm-1.0.0.0
- accelerate-llvm-native-1.0.0.0
- accelerate-llvm-ptx-1.0.0.1
- cuda-0.7.5.3
- llvm-hs-4.0.1.0
- llvm-hs-pure-4.0.0.0
